<h1><i class="fas fa-user"></i>Je crée mon compte client</h1>

<form method="post" action="<?= $requestUrl ?>/adduser" id="registrationForm">
    
    <?php if (isset($errors) == true) {
        
        echo ('<div class="error">');
        
        echo('<p><span><i class="fas fa-exclamation-triangle"></i>Il y a ' . sizeof($errors) . ' erreur(s) dans le formulaire !</span></p>');
        
        foreach($errors as $error) {
            echo('<p>' . $error . '</p>');
        }
        
        echo ('</div>');
    } ?>
    
    <fieldset>
		<legend><i class="fas fa-address-book"></i>Mes coordonnées</legend>
        
        <ul>
            <li>
                <label for="first_name">Prénom :</label>
                <input type="text" name="first_name" id="first_name" size="50"/>
            </li>
        
	        <li>
		        <label for="last_name">Nom :</label>
		        <input type="text" name="last_name" id="last_name" size="50"/>
		        <i class="fas fa-info-circle" title="Le nom ne peut comporter que des lettres, des espaces et des tirets"></i>
            </li>
            
            <li>
		        <label for="dob">Date de naissance :</label>
    			<select name="day" value="day" id="day"></select>
                <span>/</span>
    			<select name="month" value="month" id="month"/>
    				<option value="1">Janvier</option>
    				<option value="2">Février</option>
    				<option value="3">Mars</option>
    				<option value="4">Avril</option>
    				<option value="5">Mai</option>
    				<option value="6">Juin</option>
    				<option value="7">Juillet</option>
    				<option value="8">Août</option>
    				<option value="9">Septembre</option>
    				<option value="10">Octobre</option>
    				<option value="11">Novembre</option>
    				<option value="12">Décembre</option>
    			</select>
                <span>/</span>
    			<select name="year" value="year" id="year"></select>
            </li>
        
            <li>
    		    <label for="address"> Adresse :</label>
    		    <textarea type="text" name="address" rows="6" cols="60"/></textarea>
    		</li>
    		
    		<li>
    		    <label for="city">Ville :</label>
    		    <input type="text" name="city" id="city" size="50"/>
    		</li>
    		
    		<li>
    		    <label for="zipcode">Code postal :</label>
    		    <input type="text" name="zipcode" id="zipcode" size="10"/>
    		    <i class="fas fa-info-circle" title="Le code postal est composé de cinq chiffres"></i>
    		</li>
    		
    		<li>
    		    <label for="phone">Téléphone :</label>
    		    <input type="text" name="phone" id="phone" size="20"/>
    	    </li>
    	</ul>
	</fieldset>

	<fieldset>
		<legend><i class="fas fa-lock"></i>Mes informations d'authentification</legend>
        <ul>
            <li>
                <label for="email">E-mail :</label>
                <input type="text" name="email" id="email" size="50"/>
            </li>
    		<li>
    		    <label for="password">Mot de passe :</label>
    		    <input type="password" name="password" id="password" size="50"/>
    		    <i class="fas fa-info-circle" title="Le mot de passe doit contenir au moins dix caractères, dont une majuscule"></i>
    		</li>
        </ul>
	 </fieldset>

	<input class="submit" type="submit" value="Envoyer" id="confirmRegistration"/>
	<button class="cancel"><a href="<?= $requestUrl ?>/adduser">Annuler</a></button>

</form>

<script src="<?= $wwwUrl ?>/js/main.js"></script>