<h1><i class="fas fa-check-circle"></i>Commande payée</h1>

<script> window.localStorage.removeItem('cart'); </script>

<p>Votre commande a été validée. Vous serez livré dans les plus brefs délais.</p>

<p>Nous vous remerçions pour votre confiance.</p>

<p>N'hésitez pas à nous laisser des commentaires sur nos réseaux sociaux.</p>

<button class="submit"><a href="<?= $requestUrl ?>/">Accueil</a></button>