<h1><i class="fas fa-plus-circle"></i>Ajouter un produit</h1>

<form method="post" action="<?= $requestUrl ?>/admin" enctype="multipart/form-data">
    
    <fieldset>
		<legend><i class="fas fa-address-book"></i>Ajouter un produit</legend>
        <ul>
            <li>
                <label for="name">Titre :</label>
                <input type="text" name="name" id="name" size="50"/>
            </li>
        
            <li>
    		    <label for="description"> Description :</label>
    		    <textarea type="text" name="description" rows="6" cols="60"/></textarea>
    		</li>
    		<li>
    		    <label for="price">Prix :</label>
    		    <input type="text" name="price" id="price" size="20"/>
    	    </li>
    	   	<li>
    		    <label for="stock">Stock :</label>
    		    <input type="text" name="stock" id="stock" size="20"/>
    	    </li>
    	    <li>
    	        <label for="photo">Image :</label>
    	        <input type="file" name="photo">
    	    </li>
    	</ul>
	</fieldset>

	<input class="submit" type="submit" value="Ajouter"/>
	<button class="cancel"><a href="<?= $requestUrl ?>">Annuler</a></button>
</form>